name: Generate Hashes

on:
  release:
    types: [published]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: MCJack123/ghaction-generate-release-hashes@v1
        with:
          hash-type: sha256
          file-name: hashes.txt
      - uses: actions/upload-artifact@v2
        with:
          name: Asset Hashes
          path: hashes.txt
